import ReadData from '../viewModel/ReadListData';

export {ReadListData, ReadListData1}
const ReadListData: ReadData[] = [
  new ReadData('1', '明朝那些事', '12080'),
  new ReadData('2', '鬼谷子传', '10320'),
  new ReadData('3', '大秦帝国', '9801'),
  new ReadData('4', '紫禁城传奇', '8431'),
  new ReadData('5', '斗罗大陆', '7546'),
  new ReadData('6', '斗破苍穹', '7431'),
  new ReadData('7', '阿甘正传', '7187'),
  new ReadData('8', '钢铁是怎样炼成的', '7003'),
  new ReadData('9', '雾都孤儿', '6794'),
  new ReadData('10', '挪威的森林', '6721')
];

const ReadListData1: ReadData[] = [
  new ReadData('1', '明朝那些事1', '12080'),
  new ReadData('2', '鬼谷子传1', '10320'),
  new ReadData('3', '大秦帝国1', '9801'),
  new ReadData('4', '紫禁城传奇1', '8431'),
  new ReadData('5', '斗罗大陆1', '7546'),
  new ReadData('6', '斗破苍穹1', '7431'),
  new ReadData('7', '阿甘正传1', '7187'),
  new ReadData('8', '钢铁是怎样炼成的1', '7003'),
  new ReadData('9', '雾都孤儿1', '6794'),
  new ReadData('10', '挪威的森林1', '6721')
];




