// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"index":{"path":"/","id":"index","file":"index.js"},"page1":{"path":"page1","id":"page1","file":"page1.js"}},
    routeComponents: {
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.js')),
'page1': React.lazy(() => import(/* webpackChunkName: "src__pages__page1" */'../../../src/pages/page1.js')),
},
  };
}
