// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"","title":"首页","file":"@/pages/admin/index.js","parentId":"2","id":"1","originPath":"/"},"2":{"path":"/","isWrapper":true,"file":"@/components/setPageTitle.js","parentId":"@@/global-layout","id":"2"},"3":{"path":"","title":"登录","file":"@/pages/admin/login.js","parentId":"4","id":"3","originPath":"/login"},"4":{"path":"/login","isWrapper":true,"file":"@/components/setPageTitle.js","parentId":"@@/global-layout","id":"4"},"5":{"path":"","title":"欢迎","file":"@/pages/admin/welcome.js","parentId":"6","id":"5","originPath":"/welcome"},"6":{"path":"/welcome","isWrapper":true,"file":"@/components/setPageTitle.js","parentId":"@@/global-layout","id":"6"},"@@/global-layout":{"id":"@@/global-layout","path":"/","file":"@/layouts/index.js","isLayout":true}},
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__admin__index" */'@/pages/admin/index.js')),
'2': React.lazy(() => import(/* webpackChunkName: "components__setPageTitle" */'@/components/setPageTitle.js')),
'3': React.lazy(() => import(/* webpackChunkName: "p__admin__login" */'@/pages/admin/login.js')),
'4': React.lazy(() => import(/* webpackChunkName: "components__setPageTitle" */'@/components/setPageTitle.js')),
'5': React.lazy(() => import(/* webpackChunkName: "p__admin__welcome" */'@/pages/admin/welcome.js')),
'6': React.lazy(() => import(/* webpackChunkName: "components__setPageTitle" */'@/components/setPageTitle.js')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.js')),
},
  };
}
