// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"project/index":{"path":"project","id":"project/index","parentId":"@@/global-layout","file":"project/index.js"},"project/$id":{"path":"project/:id","id":"project/$id","parentId":"@@/global-layout","file":"project/$id.js"},"project/add":{"path":"project/add","id":"project/add","parentId":"@@/global-layout","file":"project/add.js"},"login":{"path":"login","id":"login","parentId":"@@/global-layout","file":"login.js"},"@@/global-layout":{"id":"@@/global-layout","path":"/","file":"@/layouts/index.js","isLayout":true}},
    routeComponents: {
'project/index': React.lazy(() => import(/* webpackChunkName: "src__pages__project__index" */'../../../src/pages/project/index.js')),
'project/$id': React.lazy(() => import(/* webpackChunkName: "src__pages__project__$id" */'../../../src/pages/project/$id.js')),
'project/add': React.lazy(() => import(/* webpackChunkName: "src__pages__project__add" */'../../../src/pages/project/add.js')),
'login': React.lazy(() => import(/* webpackChunkName: "src__pages__login" */'../../../src/pages/login.js')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.js')),
},
  };
}
